version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
      - influxdb_config:/etc/influxdb
    ports:
      - 8086:8086
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  influxdb_data:
  influxdb_config: