version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    user: 'root'
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  grafana_data:
  grafana_config:
