version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: front_nginx
    hostname: front_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front_nginx_configs:/etc/nginx/conf.d
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true