version: '3'

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_monitoring_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  prometheus_config:
  prometheus_monitoring_data: